plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id 'maven-publish' // Útil se quiser publicar localmente ou no JitPack/Maven Central
}

group = 'com.waltsoft' // Substitua pelo seu grupo/namespace
version = '0.0.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        exceptionFormat = 'full'
        events "passed", "skipped", "failed"
        showStandardStreams = (System.getenv('DEBUG') != null)
    }
}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

gradlePlugin {
    plugins {
        mermaidbPlugin {
            id = 'com.waltsoft.mermaidb' // O ID que os usuários usarão no bloco `plugins`
            implementationClass = 'com.waltsoft.mermaidb.MermaidbPlugin' // A classe principal do seu plugin
        }
    }
}
